import { StyleSheet, Dimensions } from "react-native";
import { colors } from "../../constants";
import { normalize } from "react-native-elements";
import { CUSTOM_FONT } from "../../constants/strings";
const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  viewProductDesc: {
    flex: 1,
    backgroundColor: "white",
  },
  statusWrap: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  columnContainer: {
    flexDirection: "column",
    alignSelf: "center",
  },
  columnContainer2: {
    flexDirection: "column",
    marginTop: 5,
    width: 155,
  },
  EtaWrap: {
    flexDirection: "column",
    width: "100%",
    justifyContent: "flex-end",
  },
  EtaWrap2: {
    flexDirection: "row",
    width: 180,
    marginLeft: -30,
    justifyContent: "space-between",
  },
  Eta: {
    fontWeight: "normal",
    marginTop: 0,
    marginBottom: 0,
    width: 160,
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  Etamsg: {
    color: "#898A8F",
    fontSize: 12,
    // marginLeft: 22,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  leftArrow: {
    fontSize: 18,
    top: 20,
    left: 5,
    fontWeight: "bold",
  },
  PlacedBG: {
    backgroundColor: "#46B6F540",
    color: "#46B6F540",
  },
  ConfirmedBG: {
    backgroundColor: "#46B6F540",
    color: "#46B6F540",
  },
  ShippedBG: {
    backgroundColor: "#1DD7F840",
    color: "#1DD7F840",
  },
  DliveredBG: {
    backgroundColor: "#61D8AD40",
    color: "#61D8AD40",
  },
  CreatedBG: {
    backgroundColor: "#3882E040",
  },

  PlacedSBG: {
    backgroundColor: "#46B6F5",
    color: "#46B6F5",
  },
  ConfirmedSBG: {
    backgroundColor: "#46B6F5",
    color: "#46B6F5",
  },
  ShippedSBG: {
    backgroundColor: "#1DD7F8",
    color: "#1DD7F8",
  },
  CancelledDot: {
    backgroundColor: colors.DEFAULT_RED_COLOR,
    color: colors.DEFAULT_RED_COLOR,
  },
  ShippedDot: {
    backgroundColor: "orange",
    color: "orange",
  },
  DliveredSBG: {
    backgroundColor: "#61D8AD",
    color: "#61D8AD",
  },
  DliveredDot: {
    backgroundColor: "#7ecb20",
    color: "#7ecb20",
  },
  CreatedSBG: {
    backgroundColor: "#3882E0",
    color: "#3882E0",
  },
  textProductDesc: {
    color: "#898A8F",
    fontSize: 10,
    marginLeft: 15,
    marginRight: 20,
    marginTop: 15,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  textDesc: {
    marginTop: 5,
    textAlignVertical: "center",
    fontSize: 14,
    color: "#454F63",
    marginLeft: 15,
    marginRight: 50,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  viewPriceQuantityAndTAmount: {
    flex: 1,
    marginTop: 15,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 5,
  },
  viewPrice: {
    flex: 1,
  },
  viewQuantity: {
    flex: 1,
  },
  viewTotalAmount: {
    flex: 1,
    alignItems: "flex-end",
  },
  LeftText1: {
    right: 0,
    color: "#898A8F",
    fontSize: 10,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  LeftText2: {
    color: "#454F63",
    fontSize: 14,
    marginTop: 1,
    marginBottom: 1,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  LeftText3: {
    color: "#898A8F",
    fontSize: 10,
    fontFamily: CUSTOM_FONT.HEEBO_REGULAR,
  },

  containerForIndicator: {
    flex: 2.3,
    flexDirection: "row",
    backgroundColor: "white",
  },

  stepIndicator: {
    marginTop: 10,
    paddingHorizontal: 40,
    backgroundColor: "white",
  },
  customLabelView: {
    flex: 1,
    marginTop: 10,
    marginLeft: -5,
    backgroundColor: "white",
    flexDirection: "column",
  },
  customLabelInnerView: {
    flex: 1,
    backgroundColor: "white",
    marginBottom: 20,
    marginTop: 20,
    marginLeft: 0,
    marginRight: 20,
  },
  kamLabelInnerView: {
    flex: 1,
    marginBottom: 20,
    justifyContent: "space-between",
    flexDirection: "row",
  },
  nameWrap: {
    marginBottom: 20,
    marginTop: 30,
    flexDirection: "column",
  },
  phoneWrap: {
    flexDirection: "column",
    bottom: 60,
    left: 145,
  },
  emailWrap: {
    flexDirection: "column",
    bottom: 40,
  },
  customLabelTitleTextStyle: {
    fontSize: 14,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "bold",
    color: "#454F6380",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  customLabelSelectedTitleTextStyle: {
    fontSize: 14,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  whenReturnStyle: {
    bottom: 28,
    color: "red",
    fontSize: 14,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  whenDeliverStyle: {
    bottom: 20,
    color: "red",
    fontSize: 14,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  whenDeliverStyle1: {
    bottom: 12,
    color: "red",
    fontSize: 14,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  whenReturnInitaitedStyle: {
    bottom: 9,
    color: "red",
    fontSize: 14,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  whenReturnSubTitleInitStyle: {
    bottom: 10,
    fontSize: 12,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "normal",
    color: "#898A8F",
    fontFamily: CUSTOM_FONT.HEEBO_REGULAR,
  },
  whenReturnSubTitleStyle: {
    bottom: 28,
    fontSize: 12,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "normal",
    color: "#898A8F",
    fontFamily: CUSTOM_FONT.HEEBO_REGULAR,
  },
  whenDelieverSubTitleStyle: {
    bottom: 20,
    fontSize: 12,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "normal",
    color: "#898A8F",
    fontFamily: CUSTOM_FONT.HEEBO_REGULAR,
  },
  whenDelieverSubTitleStyle1: {
    bottom: 12,
    fontSize: 12,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "normal",
    color: "#898A8F",
    fontFamily: CUSTOM_FONT.HEEBO_REGULAR,
  },
  customLabelSubTitleTextStyle: {
    fontSize: 12,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "normal",
    color: "#898A8F",
    fontFamily: CUSTOM_FONT.HEEBO_REGULAR,
  },
  nameStyle: {
    fontSize: 12,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "normal",
    color: "#454F6380",
    left: 45,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  dataStyle: {
    fontSize: 15,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "normal",
    color: "#898A8F",
    left: 45,
    width: 160,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  kamStyle: {
    fontSize: 15,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "normal",
    color: "#454F6380",
    top: 20,
    left: 45,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  itemdetailStyle: {
    fontSize: 15,
    top: 25,
    textAlign: "left",
    textAlignVertical: "center",
    fontWeight: "normal",
    color: "black",
    left: 18,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  ListViewContainer: {
    flex: 1,
    top: 15,
  },
  flatListStyle: {
    marginBottom: -80,
  },
  inVoiceView: {
    flex: 1,
    padding: 6,
    marginHorizontal: 15,
    borderRadius: 8,
    borderWidth: 0.5,
    backgroundColor: "white",
    borderColor: "#e0e0e0",
    marginVertical: normalize(7),
    height: "100%",
  },
  inVoiceView2: {
    flex: 1,
    padding: 180,
    marginTop: 10,
    marginHorizontal: 15,
    paddingHorizontal: 22,
    borderRadius: 8,
    borderWidth: 0.5,
    backgroundColor: "white",
    borderColor: "#e0e0e0",
    height: "auto",
  },
  inVoiceWrap: {
    flex: 1,
    position: "absolute",
    top: 50,
    left: 12,
    padding: 152,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: "#F7FBFF",
    backgroundColor: "#F7FBFF",
    height: "auto",
  },
  stepsWrap: {
    position: "absolute",
    flexDirection: "row",
    marginVertical: 10,
    top: 110,
    left: 32,
  },
  msgView: {
    flex: 1,
    padding: 18,
    marginHorizontal: 15,
    borderRadius: 7,
    borderWidth: 0.5,
    backgroundColor: "white",
    borderColor: "#e0e0e0",
    height: "100%",
  },
  msgWrap: {
    flexDirection: "row",
    position: "absolute",
    top: 10,
    left: 10,
  },
  wrapContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 5,
  },
  inNuView: {
    padding: 5,
    backgroundColor: "#E5F2FD",
    borderRadius: 4,
  },
  inNo: {
    color: "#898A8F",
    fontSize: 12,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  shippedmsg: {
    color: "#898A8F",
    fontSize: 13,
    left: 5,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  stepdmsg: {
    color: "#898A8F",
    fontSize: 13,
    left: 5,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  date: {
    color: "#898A8F",
    fontSize: 12,
    bottom: 10,
    left: 30,
  },
  qty: {
    marginTop: 5,
    textAlignVertical: "center",
    fontSize: 14,
    left: 10,
    color: "#454F63",
    width: "30%",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  nostyle: {
    marginTop: 5,
    textAlignVertical: "center",
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  trackWrap: {
    flexDirection: "row",
  },
  dot: {
    padding: 5,
    backgroundColor: "orange",
    width: 12,
    height: 12,
    top: 22,
    left: 5,
    borderRadius: 8,
  },
  dot2: {
    padding: 5,
    width: 12,
    height: 12,
    marginTop: 5,
    alignSelf: "center",
    marginLeft: 15,
    borderRadius: 8,
  },
  invoiceSeparater: {
    height: 0.5,
    backgroundColor: "#e0e0e0",
    marginTop: 20,
    marginHorizontal: -7,
  },
  deliverSeparater: {
    height: 0.5,
    backgroundColor: "#e0e0e0",
    marginTop: -10,
    marginHorizontal: -7,
  },
  denSeparater: {
    height: 0.5,
    backgroundColor: "#e0e0e0",
    marginBottom: 20,
    marginHorizontal: -7,
  },

  rowItem: {
    flex: 3,
    paddingVertical: 0,
    backgroundColor: "white",
  },
  title: {
    flex: 1,
    fontSize: 20,
    color: "#333333",
    paddingVertical: 16,
    fontWeight: "600",
  },
  body: {
    flex: 1,
    fontSize: 15,
    color: "#606060",
    lineHeight: 24,
    marginRight: 8,
  },
  separater: {
    height: 5,
    backgroundColor: "lightgray",
    marginTop: 15,
  },
  contactContainer: {
    backgroundColor: "transparent",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    left: 10,
    bottom: -20,
  },
  imageStyle: {
    height: 50,
    width: 50,
    resizeMode: "contain",
    marginLeft: 15,
    backgroundColor: "#898A8F1F",
  },
  viewItemIdBGStyle: {
    borderRadius: 4,
    flexDirection: "row",
    marginLeft: 15,
    marginTop: 0,
  },
  partNuView: {
    padding: 2,
    backgroundColor: "#898A8F1F",
    borderRadius: 4,
  },
  textItemsID: {
    color: "#898A8F",
    fontSize: 12,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
    textAlign: "center",
    textAlignVertical: "center",
    marginLeft: 5,
    marginRight: 5,
  },
  status: {
    fontWeight: "normal",
    marginTop: 0,
    marginBottom: 0,
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
    marginLeft: 5,
    marginRight: 5,
  },
  invoiceSeparater2: {
    height: 0.8,
    backgroundColor: "#e0e0e0",
    marginTop: 5,
  },
  topSeparator: {
    height: 1,
    width: width,
    backgroundColor: "#C6C7CC",
    marginTop: 1,
    opacity: 0.6,
  },
  bottomSeparator: {
    height: 5,
    width: width,
    marginTop: 10,
    backgroundColor: "#00000017",
    opacity: Platform.OS === "ios" ? 1 : 0.3,
  },
});
