import { StyleSheet, Dimensions, Platform } from "react-native";
import { CUSTOM_FONT } from "../../constants/strings";

import { colors } from "../../constants";
import { normalize } from "react-native-elements";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  toggleStyle: {
    alignSelf: "center",
    borderColor: "#aeaeae",
    height: 18,
    width: 18,
  },
  checkBoxStyle: {
    alignSelf: "center",
    borderColor: "red",
    height: 18,
    width: 18,
  },
  checkBoxWrapper: {
    flexDirection: "row",
  },
  wrapView: {
    justifyContent: "space-around",
    // left: normalize(60),
    alignSelf: "center",
    flexDirection: "row",
    marginRight: 12,
    width: 100,
    top: 8,
  },
  allPlant: {
    alignSelf: "center",
    fontSize: 11,
    color: "#898A8F",
    marginLeft: 12,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  my: {
    fontSize: 10,
    color: "#898A8F80",
    alignSelf: "center",
    right: 1,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  activeOrderText: {
    fontSize: 26,
    marginTop: 20,
    marginLeft: normalize(10),
    marginBottom: 10,
    fontFamily: CUSTOM_FONT.ROBOTO_BOLD,
    color: "#454F63",
  },
  topSeparator: {
    height: 1,
    width: width,
    backgroundColor: "#C6C7CC",
    marginTop: 1,
    opacity: 0.6,
  },
  TabbedContainer: {
    marginBottom: 10,
    backgroundColor: colors.BACKGROUND_COLOR,
  },
  CellUnSelectedContainer: {
    justifyContent: "center",
    alignContent: "center",
    height: 33,
    borderWidth: 0,
    borderRadius: 7,
    marginRight: 8,
  },
  CellSelectedContainer: {
    justifyContent: "center",
    alignContent: "center",
    height: 33,
    borderWidth: 0,
    borderRadius: 7,
    marginRight: 8,
  },
  item: {
    marginLeft: 12,
    marginRight: 12,
    fontSize: 12,
    color: "white",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  flatList: {
    height: 44,
    marginLeft: 18,
    marginBottom: 10,
  },
  flatListStyle: {
    backgroundColor: "white",
    marginBottom: -80,
  },
  ListViewContainer: {
    flex: 1,
    marginTop: -8,
  },
  ListRow: {
    backgroundColor: "white",
    flex: 1,
    shadowColor: "black",
    shadowOpacity: Platform.OS === "ios" ? 0.25 : 1,
    shadowRadius: 7,
    elevation: 7,
    marginBottom: 15,
    shadowOffset: {
      width: 0,
      height: 3,
    },
  },
  ListRowInnerFirstView: {
    flex: 1.4,
    padding: 15,
    backgroundColor: "transparent",
  },
  trackWrap: {
    flexDirection: "row",
  },
  nostyle: {
    marginTop: 5,
    textAlignVertical: "center",
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  wrapContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 5,
  },
  ListRowInnerSecondView: {
    flex: 1,
    alignItems: "flex-end",
    padding: 15,
    backgroundColor: "white",
  },
  LeftText1: {
    color: "#898A8F",
    fontSize: 10,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  orderNoLable: {
    color: "#898A8F",
    fontSize: 12,
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
    marginBottom: 5,
    left: 3,
    alignSelf: "center",
    marginTop: 0,
    marginBottom: 0,
  },
  orderNo: {
    color: "#898A8F",
    fontWeight: "normal",
    fontSize: 12,
    marginTop: 0,
    marginBottom: 0,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
    marginLeft: 5,
    marginRight: 5,
  },
  status: {
    fontWeight: "normal",
    marginTop: 0,
    marginBottom: 2,
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
    marginLeft: 5,
    marginRight: 5,
  },
  filterList_Text: {
    marginLeft: 0,
    marginVertical: 20,
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  headerText: {
    marginLeft: 5,
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  buttonText: {
    marginLeft: 5,
    fontSize: 14,
    marginTop: 8,
    color: "white",
    alignSelf: "center",
    justifyContent: "center",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  applyWrap: {
    width: 150,
    height: 35,
    borderRadius: 10,
    backgroundColor: "#B4B4B4",
  },
  Eta: {
    fontWeight: "bold",
    marginTop: 0,
    marginBottom: 0,
    width: 160,
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  groupedStatus: {
    fontWeight: "bold",
    marginTop: 0,
    marginBottom: 0,
    width: 160,
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
  },
  EtaWrap: {
    flexDirection: "column",
    width: "100%",
    justifyContent: "flex-end",
  },
  EtaWrap2: {
    flexDirection: "row",
    width: 180,
    marginLeft: -30,
    justifyContent: "space-between",
    // alignItems: 'center',
  },
  Etamsg: {
    color: "#898A8F",
    fontSize: 12,
    // marginLeft: 22,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  invoiceSeparater: {
    height: 0.8,
    backgroundColor: "#e0e0e0",
    marginTop: 5,
  },

  leftArrow: {
    fontSize: 18,
    top: 18,
    marginRight: 40,
    fontWeight: "bold",
  },
  leftClosedArrow: {
    fontSize: 18,
    top: 7,
    marginRight: 40,
    fontWeight: "bold",
  },
  crossArrow: {
    fontSize: 12,
    top: 3,
    left: 5,
    fontWeight: "bold",
  },
  crossArrow2: {
    fontSize: 18,
    top: 3,
    left: 0,
    color: "#454F63",
    fontWeight: "bold",
  },
  filterIcon: {
    fontSize: 18,
    top: 0,
    fontWeight: "bold",
  },
  dot: {
    padding: 5,
    width: 12,
    height: 12,
    marginTop: 0,
    alignSelf: "center",
    marginLeft: 15,
    borderRadius: 8,
  },
  mainWrap: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 2,
  },
  columnContainer: {
    flexDirection: "column",
    alignSelf: "center",
  },
  columnContainer2: {
    flexDirection: "column",
    marginTop: 5,
    width: 155,
  },
  statusWrap: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  LeftText2: {
    color: "#D9232D",
    fontWeight: "normal",
    fontSize: 16,
    marginTop: 0,
    marginBottom: 0,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
    marginLeft: 5,
    marginRight: 5,
  },
  nextDays: {
    color: "black",
    fontSize: 14,
    alignSelf: "center",
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  weekDays: {
    color: "black",
    fontSize: 14,
    marginLeft: 22,
    marginBottom: 5,
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  showText: {
    color: "black",
    fontSize: 14,
    marginBottom: 10,
    alignSelf: "center",
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  filterText: {
    color: "black",
    fontSize: 14,
    backgroundColor: "#f5f5f9",
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  filterView: {
    flexDirection: "row",
    padding: 5,
    paddingHorizontal: 10,
    marginBottom: 10,
    backgroundColor: "white",
    borderRadius: 5,
  },
  clearFilterView: {
    width: 95,
    height: 20,
    backgroundColor: colors.BACKGROUND_COLOR,
  },
  clearfilterWrap: {
    flexDirection: "row",
    marginRight: 5,
    alignSelf: "center",
  },
  nextDays1: {
    color: "black",
    fontWeight: "normal",
    fontSize: 14,
    marginHorizontal: 1,
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  otherDays: {
    color: "black",
    fontWeight: "normal",
    fontSize: 14,
    bottom: 6,
    left: 20,
    fontWeight: "bold",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  count: {
    color: "black",
    fontWeight: "normal",
    fontSize: 14,
    alignSelf: "center",
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  count1: {
    color: "black",
    fontWeight: "bold",
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  rightArrowStyle: {
    width: 24,
    height: 24,
    marginRight: normalize(15),
  },
  LeftText3: {
    color: "#898A8F",
    fontWeight: "normal",
    fontSize: 12,
    marginBottom: 15,
    fontFamily: CUSTOM_FONT.HEEBO_REGULAR,
  },
  pendingQty: {
    color: "#898A8F",
    fontWeight: "normal",
    fontSize: 12,
    marginLeft: 5,
    alignSelf: "center",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  LeftText4: {
    color: "#454F63",
    fontSize: 14,
    marginTop: 0,
    alignSelf: "center",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  nextArrowStyle: {
    width: 24,
    height: 24,
    marginRight: normalize(10),
  },
  ButtonViewStyle: {
    color: "#454F63",
    marginTop: 10,
    marginBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 0,
    borderRadius: 7,
    borderColor: "transparent",
  },
  ButtonTextStyle: {
    textAlign: "center",
    fontSize: 12,
    textTransform: "uppercase",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
    color: "#454F63",
    marginLeft: 10,
    marginRight: 0,
  },

  NoDataAvailableStyle: {
    flex: 1,
    textAlign: "center",
  },
  DataAvailableStyle: {
    height: 0,
  },
  PlacedBG: {
    backgroundColor: "#46B6F540",
    color: "#46B6F540",
  },
  ConfirmedBG: {
    backgroundColor: "#46B6F540",
    color: "#46B6F540",
  },
  ShippedBG: {
    backgroundColor: "#1DD7F840",
    color: "#1DD7F840",
  },
  DliveredBG: {
    backgroundColor: "#61D8AD40",
    color: "#61D8AD40",
  },
  CreatedBG: {
    backgroundColor: "#3882E040",
  },

  PlacedSBG: {
    backgroundColor: "#46B6F5",
    color: "#46B6F5",
  },
  ConfirmedSBG: {
    backgroundColor: "#46B6F5",
    color: "#46B6F5",
  },
  ShippedSBG: {
    backgroundColor: "#1DD7F8",
    color: "#1DD7F8",
  },
  CancelledDot: {
    backgroundColor: colors.DEFAULT_RED_COLOR,
    color: colors.DEFAULT_RED_COLOR,
  },

  ShippedDot: {
    backgroundColor: "orange",
    color: "orange",
  },
  DliveredSBG: {
    backgroundColor: "#61D8AD",
    color: "#61D8AD",
  },
  DliveredDot: {
    backgroundColor: "#7ecb20",
    color: "#7ecb20",
  },
  CreatedSBG: {
    backgroundColor: "#3882E0",
    color: "#3882E0",
  },
  contactContainer: {
    height: 50,
    alignItems: "flex-end",
    justifyContent: "flex-end",
    backgroundColor: "red",
  },
  viewItemIdBGStyle: {
    // backgroundColor:'#898A8F1F',
    borderRadius: 4,
    flexDirection: "row",
    marginLeft: 10,
  },
  viewOrderNumberBGStyle: {
    borderRadius: 4,
    flexDirection: "row",
    //  marginLeft: 0,
  },
  warpper: {
    flexDirection: "row",
    marginLeft: 10,
    height: 40,
    marginBottom: 10,
  },
  orderNoView: {
    padding: 2,
    backgroundColor: "#E5F2FD",
    borderRadius: 4,
    flexDirection: "row",
    alignSelf: "center",
  },
  stripView: {
    padding: 6,
    marginHorizontal: 20,
    backgroundColor: "#D9232D14",
    borderRadius: 8,
    bottom: 10,
    borderWidth: 0.9,
    borderColor: "orange",
  },
  wrap: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  Shippedwrap: {
    flexDirection: "row",
    marginHorizontal: 20,
    justifyContent: "space-between",
  },
  showwrap: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  partNuView: {
    padding: 2,
    borderRadius: 4,
    marginLeft: 10,
  },
  textItemsID: {
    color: "#898A8F",
    fontSize: 12,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
    textAlign: "left",
    textAlignVertical: "center",
    marginLeft: 5,
    marginRight: 5,
  },
  statusItem: {
    color: "#898A8F",
    fontSize: 12,
    fontWeight: "bold",
    fontFamily: CUSTOM_FONT.HEEBO_BOLD,
    textAlign: "left",
    textAlignVertical: "center",
    marginLeft: 0,
    marginRight: 5,
  },
  textRunning: {
    //color:'#FF0000',
    fontSize: 10,
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
    //textAlign: 'left',
    textAlignVertical: "center",
    marginTop: -10,
    //marginBottom: 20
  },
  viewProductDesc: {
    flex: 1,
    flexDirection: "row",
    marginLeft: 15,
    marginBottom: 20,
  },
  imageStyle: {
    marginTop: 3,
    height: 75,
    width: 75,
    resizeMode: "contain",
    backgroundColor: "#898A8F1F",
  },
  textDesc: {
    flex: 1,
    marginTop: 5,
    textAlignVertical: "center",
    marginLeft: 10,
    width: 250,
    fontSize: 14,
    color: "#454F63",
    fontFamily: CUSTOM_FONT.HEEBO_MEDIUM,
  },
  LastLabelStyle: {
    color: "#898A8F",
    fontSize: 10,
    fontFamily: CUSTOM_FONT.HEEBO_REGULAR,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 10,
    marginTop: 10,
  },
  buttonHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 30,
    // marginTop: 10,
    marginBottom: 30,
  },
  contactPopView: {
    flex: 1,
    backgroundColor: "transparent",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    position: "absolute",
    zIndex: 9,
    left: 10,
    bottom: -20,
  },
  clearAll: {
    justifyContent: "center",
    paddingTop: 14,
    height: 50,
    marginLeft: normalize(15),
  },
  clearText: { fontSize: normalize(10), fontFamily: CUSTOM_FONT.HEEBO_REGULAR },
  orderlistPageInnerWrap: {
    paddingHorizontal: normalize(8),
    paddingBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  multiSelectDrop: {
    width: normalize(180),
    backgroundColor: "#f5f5f9",
    marginBottom: -5,
    marginTop: 2,
  },
  clearWrap: { flexDirection: "row", justifyContent: "flex-end" },
});
