// This file contains all the constant related to the action of sagas

export const ActionTypes = {
    GET_INITIATE_LOGIN: 'GET_INITIATE_LOGIN',
    SET_INITIATE_LOGIN: 'SET_INITIATE_LOGIN',
    GET_INITIATE_LOGOUT: 'GET_INITIATE_LOGOUT',
    GLOBAL_ERROR: 'GLOBAL_ERROR',
    IS_LOGGED_IN: 'IS_LOGGED_IN',

    SUBMIT_LOGIN_FORM: 'SUBMIT_LOGIN_FORM',
    SUBMIT_GOOGLE_LOGIN_FORM: 'SUBMIT_GOOGLE_LOGIN_FORM',
    IS_LOGIN_LOADING: 'IS_LOGIN_LOADING',
    SET_LOGIN_LOADING: 'SET_LOGIN_LOADING',
    GET_USERDATA_LOCAL: 'GET_USERDATA_LOCAL',
    USER_SIGN_OUT: 'USER_SIGN_OUT',

    GET_DASHBOARD_DATA: 'GET_DASHBOARD_DATA',
    DASHBOARD_DATA_RECEIVED: 'DASHBOARD_DATA_RECEIVED',
    IS_HOME_LOADING: 'IS_HOME_LOADING',
    GET_LOGIN_USER_SESSION_DATA: 'GET_LOGIN_USER_SESSION_DATA',
    SET_HOME_GET_SESSION_DATA: 'SET_HOME_GET_SESSION_DATA',
    SUMMARY_DATA_RECEIVED: 'SUMMARY_DATA_RECEIVED',
    GET_OVERALL_SUMMARY_DATA: 'GET_OVERALL_SUMMARY_DATA',
    GET_LAST_SIX_MONTH_DATA: 'GET_LAST_SIX_MONTH_DATA',
    LAST_SIX_MONTH_DATA_RECEIVED: 'LAST_SIX_MONTH_DATA_RECEIVED',
    GET_SPEND_BY_CATEGORY_DATA: 'SPEND_BY_CATEGORY_DATA',
    SPEND_BY_CATEGORY_DATA_RECEIVED: 'SPEND_BY_CATEGORY_DATA_RECEIVED',
    GET_SPEND_BY_ALL_CATEGORY_DATA: 'GET_SPEND_BY_ALL_CATEGORY_DATA',
    SPEND_BY_ALL_CATEGORY_DATA_RECEIVED: 'SPEND_BY_ALL_CATEGORY_DATA_RECEIVED',
    GET_OTIF_VIEW_DATA: 'GET_OTIF_VIEW_DATA',
    OTIF_VIEW_DATA_RECEIVED: 'OTIF_VIEW_DATA_RECEIVED',
    GET_TOP_ITEM_DATA: 'GET_TOP_ITEM_DATA',
    TOP_ITEM_DATA_RECEIVED: 'TOP_ITEM_DATA_RECEIVED',
    GET_TOP_PLANT_DATA: 'GET_TOP_PLANT_DATA',
    TOP_PLANT_DATA_RECEIVED: 'TOP_PLANT_DATA_RECEIVED',
    GET_ITEM_COUNT_DATA: 'GET_ITEM_COUNT_DATA',
    ITEM_COUNT_DATA_RECEIVED: 'ITEM_COUNT_DATA_RECEIVED',
    GET_COMPANY_DATA: 'GET_COMPANY_DATA',
    COMPANY_GET_RECEIVED: 'COMPANY_GET_RECEIVED',

    SUBMIT_FORGOT_PASSWORD_FORM: 'SUBMIT_FORGOT_PASSWORD_FORM',
    SET_FORGOT_PASSWORD_LOADING: 'SET_FORGOT_PASSWORD_LOADING',
    FORGOT_PASSWORD_DATA_RECEIVED: 'FORGOT_PASSWORD_DATA_RECEIVED',

    SUBMIT_RESET_PASSWORD_FORM: 'SUBMIT_RESET_PASSWORD_FORM',
    SET_RESET_PASSWORD_LOADING: 'SET_RESET_PASSWORD_LOADING',
    RESET_PASSWORD_DATA_RECEIVED: 'RESET_PASSWORD_DATA_RECEIVED',
    FLAG_SET_OF_FORGOT: 'FLAG_SET_OF_FORGOT',
    CHANGE_FLAG_VALUE: 'CHANGE_FLAG_VALUE',

    GET_SEARCHED_ORDER_DATA: 'GET_SEARCHED_ORDER_DATA',
    SEARCHED_ORDER_DATA_RECEIVED: 'SEARCHED_ORDER_DATA_RECEIVED',
    IS_SEARCHED_ORDER_LOADING: 'IS_SEARCHED_ORDER_LOADING',

    GET_ORDERLIST_DATA: 'GET_ORDERLIST_DATA',
    GET_UPCOMING_DATA: 'GET_UPCOMING_DATA',
    GET_SUBSTATUS_FILTER_DATA: 'GET_SUBSTATUS_FILTER_DATA',
    GET_ORDERLIST_DELAY_DATA: 'GET_ORDERLIST_DELAY_DATA',
    UPCOMINGLIST_DATA_RECEIVED: 'UPCOMINGLIST_DATA_RECEIVED',
    FILTER_SUBSTATUS_DATA_RECEIVED: 'FILTER_SUBSTATUS_DATA_RECEIVED',
    ORDERLIST_DATA_RECEIVED: 'ORDERLIST_DATA_RECEIVED',
    FILTER_SUBSTATUS_BUCKET_RECEIVED: 'FILTER_SUBSTATUS_BUCKET_RECEIVED',
    ORDERLIST_BUCKET_RECEIVED: 'ORDERLIST_BUCKET_RECEIVED',
    IS_CHECK_DATA: 'IS_CHECK_DATA',
    START_DATE: 'START_DATE',
    IS_ORDERLISTING_LOADING: 'IS_ORDERLISTING_LOADING',
    SELECTED_TAB_VALUE: 'SELECTED_TAB_VALUE',
    IS_USER_FILTER: 'IS_USER_FILTER',
    FILTER_STATE_DATA: 'FILTER_STATE_DATA',
    START_AND_END_DATE: 'START_AND_END_DATE',
    ACTIVE_USER_FILTER: 'ACTIVE_USER_FILTER',
    CLEAR_ORDER_LIST_DATA: 'CLEAR_ORDER_LIST_DATA',

    GET_ORDERLIST_DETAIL_DATA: 'GET_ORDERLIST_DETAIL_DATA',
    ORDERLIST_DETAIL_DATA_RECEIVED: 'ORDERLIST_DETAIL_DATA_RECEIVED',
    IS_ORDERLISTING_DETAIL_LOADING: 'IS_ORDERLISTING_DETAIL_LOADING',
    GET_USER_FILTER_DATA: 'GET_USER_FILTER_DATA',
    USER_FILTER_DATA_RECEIVED: 'USER_FILTER_DATA_RECEIVED',

    RUN_ACTIVITY: 'RUN_ACTIVITY',

    GET_ITEM_TRACK_DETAIL_DATA: 'GET_ITEM_TRACK_DETAIL_DATA',
    ITEM_TRACK_DATA_RECEIVED: 'ITEM_TRACK_DATA_RECEIVED',

    GET_INVOICE_REQUEST_DATA: 'GET_INVOICE_REQUEST_DATA',
    INVOICE_REQUEST_RECEIVED: 'INVOICE_REQUEST_RECEIVED',
    GET_INVOICE_TRACK_REQUEST: 'GET_INVOICE_TRACK_REQUEST',
    INVOICE_TRACK_DATA_RECEIVED: 'INVOICE_TRACK_DATA_RECEIVED',
    GET_NORMAL_ORDER_REQUEST: 'GET_NORMAL_ORDER_REQUEST',
    NORMAL_ORDER_DATA_RECEIVED: 'NORMAL_ORDER_DATA_RECEIVED',

    GET_SEND_MESSAGE_RESPONSE: 'GET_SEND_MESSAGE_RESPONSE',
    SEND_MESSAGE_DATA_RECEIVED: 'SEND_MESSAGE_DATA_RECEIVED',

    ERROR_INITIATE_LOGOUT: 'ERROR_INITIATE_LOGOUT',

    SET_USER_DATA: 'SET_USER_DATA',

    GET_LOGIN_STATUS: 'GET_LOGIN_STATUS',
    SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',

    GET_USER_DATA: 'GET_USER_DATA',
    LOGOUT_USER_DATA: 'LOGOUT_USER_DATA',

    START_INITIATE_LOGIN: 'START_INITIATE_LOGIN',
    LOGOUT_USER_LOGIN: 'LOGOUT_USER_LOGIN',

    SAVE_LOGIN_STATUS: 'SAVE_LOGIN_STATUS',

    SAVE_USER_DATA: 'SAVE_USER_DATA',

    START_FORGOT_PASSWORD: 'START_FORGOT_PASSWORD',
    GET_FORGOT_PASSWORD: 'GET_FORGOT_PASSWORD',
    SET_FORGOT_PASSWORD: 'SET_FORGOT_PASSWORD',

    ERROR_INITIATE_LOGIN: 'ERROR_INITIATE_LOGIN',

    ERROR_FORGOT_PASSWORD: 'ERROR_FORGOT_PASSWORD',

    ERROR_OTP_VERIFICATION: 'ERROR_OTP_VERIFICATION',
}
